name: env_evcap
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.7.22=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=41.0.3=py39hdda0065_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - faiss-cpu=1.7.4=py3.9_h8c27c75_0_cpu
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_1
  - libfaiss=1.7.4=h2bc3f7f_0_cpu
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_0
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.24.3=py39h14f4228_0
  - numpy-base=1.24.3=py39h31eccc5_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.11=h7f8727e_2
  - pillow=10.0.1=py39ha6cbd5a_0
  - pip=23.3=py39h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - pytorch=1.12.1=py3.9_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py39h06a4308_0
  - setuptools=68.0.0=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py39_cu113
  - torchvision=0.13.1=py39_cu113
  - urllib3=1.26.16=py39h06a4308_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - accelerate==0.16.0
    - aiofiles==23.2.1
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - altair==5.1.2
    - antlr4-python3-runtime==4.9.3
    - anyio==3.7.1
    - appdirs==1.4.4
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.0
    - async-lru==2.0.4
    - async-timeout==4.0.2
    - attrs==22.2.0
    - babel==2.13.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - bitsandbytes==0.37.0
    - bleach==6.1.0
    - blis==0.7.11
    - braceexpand==0.1.7
    - catalogue==2.0.10
    - cchardet==2.1.7
    - chardet==5.1.0
    - click==8.1.7
    - comm==0.1.4
    - confection==0.1.3
    - contourpy==1.0.7
    - cycler==0.11.0
    - cymem==2.0.8
    - datasets==2.14.6
    - debugpy==1.8.0
    - decorator==5.1.1
    - decord==0.6.0
    - defusedxml==0.7.1
    - diffusers==0.21.4
    - dill==0.3.7
    - docker-pycreds==0.4.0
    - einops==0.7.0
    - exceptiongroup==1.1.3
    - executing==2.0.0
    - fairscale==0.4.13
    - fastapi==0.104.0
    - fastjsonschema==2.18.1
    - ffmpy==0.3.1
    - filelock==3.9.0
    - fonttools==4.38.0
    - fqdn==1.5.1
    - frozenlist==1.3.3
    - fsspec==2023.9.2
    - gitdb==4.0.11
    - gitpython==3.1.40
    - gradio==3.24.1
    - gradio-client==0.0.8
    - h11==0.14.0
    - httpcore==0.18.0
    - httpx==0.25.0
    - huggingface==0.0.1
    - huggingface-hub==0.18.0
    - imageio==2.31.5
    - importlib-metadata==6.8.0
    - importlib-resources==5.12.0
    - intel-openmp==2023.2.0
    - iopath==0.1.10
    - ipdb==0.13.13
    - ipykernel==6.25.2
    - ipython==8.16.1
    - isoduration==20.11.0
    - jedi==0.19.1
    - jinja2==3.1.2
    - joblib==1.3.2
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.19.1
    - jsonschema-specifications==2023.7.1
    - jupyter-client==8.4.0
    - jupyter-core==5.4.0
    - jupyter-events==0.8.0
    - jupyter-lsp==2.2.0
    - jupyter-server==2.8.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.7
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.25.0
    - kiwisolver==1.4.4
    - langcodes==3.3.0
    - lazy-loader==0.3
    - linkify-it-py==2.0.2
    - llvmlite==0.41.1
    - markdown-it-py==2.2.0
    - markupsafe==2.1.3
    - matplotlib==3.7.0
    - matplotlib-inline==0.1.6
    - mdit-py-plugins==0.3.3
    - mdurl==0.1.2
    - mistune==3.0.2
    - mkl==2023.2.0
    - mpmath==1.3.0
    - multidict==6.0.4
    - multiprocess==0.70.15
    - murmurhash==1.0.10
    - nbclient==0.8.0
    - nbconvert==7.9.2
    - nbformat==5.9.2
    - nest-asyncio==1.5.8
    - networkx==3.2
    - nltk==3.8.1
    - notebook==7.0.6
    - notebook-shim==0.2.3
    - numba==0.58.1
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.3.52
    - nvidia-nvtx-cu12==12.1.105
    - omegaconf==2.3.0
    - openai==0.27.0
    - opencv-python==4.7.0.72
    - orjson==3.9.9
    - overrides==7.4.0
    - packaging==23.0
    - pandas==2.1.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pathy==0.10.2
    - peft==0.5.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==3.11.0
    - portalocker==2.8.2
    - preshed==3.0.9
    - prometheus-client==0.17.1
    - prompt-toolkit==3.0.39
    - protobuf==4.24.4
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==14.0.0
    - pycocoevalcap==1.2
    - pycocotools==2.0.6
    - pydantic==1.10.13
    - pydub==0.25.1
    - pygments==2.16.1
    - pynndescent==0.5.10
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - python-multipart==0.0.6
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - pyzmq==25.1.1
    - referencing==0.30.2
    - regex==2022.10.31
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.10.6
    - safetensors==0.4.0
    - scikit-image==0.22.0
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - semantic-version==2.10.0
    - send2trash==1.8.2
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.99
    - sentry-sdk==1.32.0
    - setproctitle==1.3.3
    - smart-open==6.4.0
    - smmap==5.0.1
    - sniffio==1.3.0
    - soupsieve==2.5
    - spacy==3.5.1
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - srsly==2.4.8
    - stack-data==0.6.3
    - starlette==0.27.0
    - sympy==1.12
    - tbb==2021.10.0
    - tenacity==8.2.2
    - terminado==0.17.1
    - thinc==8.1.12
    - threadpoolctl==3.2.0
    - tifffile==2023.9.26
    - timm==0.6.13
    - tinycss2==1.2.1
    - tokenizers==0.13.2
    - tomli==2.0.1
    - toolz==0.12.0
    - torch==2.1.0
    - tornado==6.3.3
    - tqdm==4.64.1
    - traitlets==5.11.2
    - transformers==4.28.0
    - triton==2.1.0
    - typer==0.7.0
    - types-python-dateutil==2.8.19.14
    - typing-extensions==4.8.0
    - tzdata==2023.3
    - uc-micro-py==1.0.2
    - umap-learn==0.5.4
    - uri-template==1.3.0
    - uvicorn==0.23.2
    - wandb==0.15.12
    - wasabi==1.1.2
    - wcwidth==0.2.8
    - webcolors==1.13
    - webdataset==0.2.48
    - webencodings==0.5.1
    - websocket-client==1.6.4
    - websockets==11.0.3
    - xxhash==3.4.1
    - yarl==1.8.2
    - zipp==3.14.0
